### ISSUE TITLE
nit: requirements should get cleaned up

### ISSUE THREAD

**Issue by willkg** [mozilla/plugincheck#4]
There's a `requirements.txt` file and a `requirements/` directory with a `default.txt` and a `dev.txt` files in it.

I vote clean that up so there's just the `requirements.txt` file with the contents of `default.txt` in it and then nix the directory.

If you need to do dev-specific requirements, put them in `requirements-dev.txt`.

The compelling reason to switch to having a directory of requirements files is if there are multiple scenarios. Like if you've got postgres requirements and mysql requirements or test requirements that you don't want installed with dev requirements.

Generally, the simpler you keep it, the easier it is to document and use.

**Comment by rlr** [comment]
fixord f646b6044e07174e8376798942c3af3827ce541f
