### ISSUE TITLE
manage.py runserver line in docs

### ISSUE THREAD

**Issue by willkg** [mozilla/plugincheck#6]
http://plugincheck.readthedocs.org/en/latest/getting_started.html#editing-code-and-testing-it

That says to do:

```
$ ./manage.py runserver 0.0.0.0:8000
```

But if you're running it locally rather than in a vagrant vm, you can just do:

```
$ ./manage.py runserver
```

**Comment by rlr** [comment]
Thank you! 5581b96b574c7a6cb0680a30a37530858c30c3cc
